#! /bin/sh

# This script puts the TeleCaster services to
# suspend before going to sleep. Otherwise it may be in a weird state
# after wakeup, namely everything looks fine from various AT commands,
# the modem is registered to the cell network and reports a suitable
# signal strength, but attempting to dial out by atdt*99# or, it seems,
# any other number and the modem just responds instantly with NO CARRIER.


#if [ ! -x /sys/bus/usb/devices/${BUS}-${DEVICE}/power/level ]; then
#    exit 0
#fi

case $1 in
     suspend|suspend_hybrid|hibernate)
	/etc/init.d/telecaster stop
        sleep 1
        /etc/init.d/jackd stop
        ;;
     resume|thaw)
	/etc/init.d/jackd start
        /etc/init.d/telecaster start
        ;;
esac
