#!/bin/sh
### BEGIN INIT INFO
# Provides:          telecaster-video-relay
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init script for the telecaster video relay
### END INIT INFO


DAEMON=deefuzzer
USERNAME=telecaster
CONFFILE="/etc/telecaster/deefuzzer/telecaster_webm_monitor.yaml"
LOG=/var/log/telecaster/deefuzzer-video-daemon.log
PIDFILE=/var/run/telecaster-video-relay.pid

. /lib/lsb/init-functions

case "$1" in
	start)
	    log_begin_msg "Starting telecaster video streaming relay:" "telecaster"
            su -c "$DAEMON $CONFFILE &" $USERNAME
            pid=`pgrep -u ${USERNAME} -f "$DAEMON $CONFFILE"`
	    if [ pid = '' ]; then
 		log_failure_msg "TeleCaster video daemon can't be started! Check logfile: $LOG"
            else
                echo $pid > $PIDFILE
 	    fi
	;;
	stop)
	        log_begin_msg "Stopping telecaster video streaming relay:" "telecaster"
                pid=`cat $PIDFILE | sed -e 's/\s.*//'|head -n1`
		if [ ! pid = '' ]; then
                        kill -9 $pid
        		log_end_msg 0
    		else
	    		log_end_msg 1
	    		exit 1
	    	fi
                rm $PIDFILE
		;;
	try-restart)
		if test -e $PIDFILE ; then
			pid=`cat $PIDFILE | sed -e 's/\s.*//'|head -n1`
			PIDDIR=/proc/$pid
			if [ -d ${PIDDIR} -a  "$(readlink -f ${PIDDIR}/exe)" = "${DAEMON}" ]; then
				$0 restart
				exit 0
			fi
		fi
		test -f /etc/rc`/sbin/runlevel | cut -d' ' -f2`.d/S*vncserver* && $0 start
		;;

	*)
		log_warning_msg "Usage: /etc/init.d/telecaster-audio {start|stop}"
		log_warning_msg "  start - starts system-wide vncserver service"
		log_warning_msg "  stop  - stops system-wide vncserver service"
		exit 1
		;;
esac

exit 0
