#!/bin/sh
### BEGIN INIT INFO
# Provides:          vncserver
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init script for vncserver with RT capabilities
### END INIT INFO


DAEMON=/usr/bin/vncserver
USER=
OPTIONS=""
LOG=/var/log/vncserver.log
PIDFILE=/var/run/vncserver.pid
PORT=1

test -f /etc/default/vncserver || exit 0
. /etc/default/vncserver

VNCHOME=/home/$USER

if [ ! "x$START_DAEMON" = "xyes" -a ! "$1" = "stop" ]; then
	echo "Edit /etc/default/vncserver to start vncserver"
	exit 0
fi

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
	start)	
	    log_begin_msg "Starting vncserver audio server:" "vncserver"
            echo $DAEMON $OPTIONS :$PORT' &' > $VNCHOME/.vncserverinit
            chmod +x $VNCHOME/.vncserverinit
            su -c $VNCHOME/.vncserverinit $USER > ${LOG}
	    sleep 2
            pid=`pgrep -u ${USER} vncserver` 
	    if [ pid = '' ]; then
 		        log_failure_msg "Vncserver daemon can't be started! Check logfile: ${LOG}"
            else
                echo $pid > $PIDFILE
 	        fi
 	        
		;;
	stop)
	        log_begin_msg "Stopping vncserver audio server:" "vncserver"
                pid=`cat $PIDFILE | sed -e 's/\s.*//'|head -n1` 
		if [ ! pid = '' ]; then
			su -c "pkill -9 edcast_jack" $USER
			sleep 1
                        su -c "vncserver -kill :$PORT" $USER
        		log_end_msg 0
    		else
	    		log_end_msg 1
	    		exit 1
	    	fi
                rm $PIDFILE
		;;
	try-restart)
		if test -e $PIDFILE ; then
			pid=`cat $PIDFILE | sed -e 's/\s.*//'|head -n1`
			PIDDIR=/proc/$pid
			if [ -d ${PIDDIR} -a  "$(readlink -f ${PIDDIR}/exe)" = "${DAEMON}" ]; then
				$0 restart
				exit 0
			fi
		fi
		test -f /etc/rc`/sbin/runlevel | cut -d' ' -f2`.d/S*vncserver* && $0 start
		;;

	*)
		log_warning_msg "Usage: /etc/init.d/vncserver {start|stop|restart|force-reload|awaken|debug-run}"
		log_warning_msg "  start - starts system-wide vncserver service"
		log_warning_msg "  stop  - stops system-wide vncserver service"
		log_warning_msg "  restart, force-reload - starts a new system-wide vncserver service"
		log_warning_msg "  awaken - tell system-wide vncserver to start a poll cycle immediately"
		log_warning_msg "  debug-run [strace [strace options...]] - start a debug run of the"
		log_warning_msg "    system-wide vncserver service, optionally running it under strace"
		exit 1
		;;
esac

exit 0
