#!/bin/bash

gst-launch v4l2src device=/dev/video0 ! video/x-raw-yuv,width=640, height=480 \
	! queue ! ffmpegcolorspace \
	! queue ! theoraenc quality=20 ! mux. \
	alsasrc device=hw:0,0 ! audio/x-raw-int,rate=44100,channels=2,depth=16 \
	!  queue ! audioconvert ! audio/x-raw-float,rate=44100,channels=2,depth=16 ! queue ! vorbisenc ! mux. \
	oggmux name=mux ! filesink location=/var/www/test/test.ogg \

# ! queue ! videorate ! video/x-raw-yuv, framerate=25/1 \
#jackaudiosrc connect=1 ! queue ! audioconvert ! audio/x-raw-int,rate=44100,channels=1,width=16