#!/bin/sh
### BEGIN INIT INFO
# Provides:          stream-m
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init-Script for system wide fetchmail daemon
### END INIT INFO

DAEMON=/usr/local/bin/stream-m
USER=""
CONF="/etc/stream-m/server.conf"
LOG=/var/log/stream-m.log
PIDFILE=/var/run/stream-m.pid

test -f /etc/default/stream-m || exit 0
. /etc/default/stream-m

STREAMMHOME=/home/$USER

if [ ! "x$START_DAEMON" = "xyes" -a ! "$1" = "stop" ]; then
	echo "Edit /etc/default/stream-m to start stream-m"
	exit 0
fi

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
	start)	
	        log_begin_msg "Starting stream-m video server:" "stream-m"
            echo $DAEMON $CONF ' &' > $STREAMMHOME/.stream-m-init
            chmod +x $STREAMMHOME/.stream-m-init
            su -c $STREAMMHOME/.stream-m-init $USER > ${LOG}
	        sleep 2
            pid=`pgrep -u ${USER} stream-m` 
	        if [ pid = '' ]; then
 		        log_failure_msg "Stream-m daemon can't be started! Check logfile: ${LOG}"
            else
                echo $pid > $PIDFILE
 	        fi
 	        
		;;
	stop)
	        log_begin_msg "Stopping stream-m video server:" "stream-m"
                pid=`cat $PIDFILE | sed -e 's/\s.*//'|head -n1` 
		if [ ! pid = '' ]; then
                        kill -9 $pid
                        pkill -9 -f 'stream-m'
        		log_end_msg 0
    		else
	    		log_end_msg 1
	    		exit 1
	    	fi
                rm $PIDFILE
		;;
	try-restart)
		if test -e $PIDFILE ; then
			pid=`cat $PIDFILE | sed -e 's/\s.*//'|head -n1`
			PIDDIR=/proc/$pid
			if [ -d ${PIDDIR} -a  "$(readlink -f ${PIDDIR}/exe)" = "${DAEMON}" ]; then
				$0 restart
				exit 0
			fi
		fi
		test -f /etc/rc`/sbin/runlevel | cut -d' ' -f2`.d/S*stream-m* && $0 start
		;;

	*)
		log_warning_msg "Usage: /etc/init.d/stream-m {start|stop|restart|force-reload|awaken|debug-run}"
		log_warning_msg "  start - starts system-wide stream-m service"
		log_warning_msg "  stop  - stops system-wide stream-m service"
		log_warning_msg "  restart, force-reload - starts a new system-wide stream-m service"
		log_warning_msg "  awaken - tell system-wide stream-m to start a poll cycle immediately"
		log_warning_msg "  debug-run [strace [strace options...]] - start a debug run of the"
		log_warning_msg "    system-wide stream-m service, optionally running it under strace"
		exit 1
		;;
esac

exit 0
