#!/bin/sh
### BEGIN INIT INFO
# Provides:          vncserver
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init script for the audio vncserver
### END INIT INFO


DAEMON=/usr/bin/vncserver
USER=
OPTIONS=""
LOG=/var/log/telecaster/vncserver.log
PIDFILE=/var/run/vncserver.pid
PORT=2

test -f /etc/default/telecaster || exit 0
. /etc/default/telecaster

VNCHOME=/home/$USER

if [ ! "x$START_DAEMON" = "xyes" -a ! "$1" = "stop" ]; then
	echo "Edit /etc/default/telecaster to start telecaster vncserver"
	exit 0
fi

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
	start)
	    log_begin_msg "Starting telecaster streaming vncserver:" "telecaster"
            su -c "$DAEMON $OPTIONS :$PORT > $LOG &" $USER
            sleep 10
            #su -c "deefuzzer /etc/telecaster/deefuzzer/telecaster_mp3_monitor.yaml > /dev/null &" $USER
            #su -c "deefuzzer /etc/telecaster/deefuzzer/telecaster_webm_monitor.yaml > /dev/null &" $USER
            pid=`pgrep -u ${USER} vncserver`
	    if [ pid = '' ]; then
 		        log_failure_msg "TeleCaster daemon can't be started! Check logfile: $LOG"
            else
                echo $pid > $PIDFILE
 	        fi

		;;
	stop)
	        log_begin_msg "Stopping telecaster streaming vncserver:" "telecaster"
                pid=`cat $PIDFILE | sed -e 's/\s.*//'|head -n1`
		if [ ! pid = '' ]; then
			#su -c "pkill -9 -f \"/usr/local/bin/deefuzzer /etc/telecaster/deefuzzer/telecaster_mp3_monitor.yaml\" " $USER
			#su -c "pkill -9 -f \"/usr/local/bin/deefuzzer /etc/telecaster/deefuzzer/telecaster_webm_monitor.yaml\" " $USER
			su -c "pkill -9 -f \"python /usr/local/share/telecaster/scripts/monitor_check.py\" "
                    	su -c "pkill -9 gst-launch-0.10" $USER
			sleep 1
                        su -c "vncserver -kill :$PORT" $USER
        		log_end_msg 0
	    	else
	    		log_end_msg 1
	    		exit 1
	    	fi
                rm $PIDFILE
		;;
	try-restart)
		if test -e $PIDFILE ; then
			pid=`cat $PIDFILE | sed -e 's/\s.*//'|head -n1`
			PIDDIR=/proc/$pid
			if [ -d ${PIDDIR} -a  "$(readlink -f ${PIDDIR}/exe)" = "${DAEMON}" ]; then
				$0 restart
				exit 0
			fi
		fi
		test -f /etc/rc`/sbin/runlevel | cut -d' ' -f2`.d/S*vncserver* && $0 start
		;;

	*)
		log_warning_msg "Usage: /etc/init.d/telecaster {start|stop|restart|force-reload|awaken|debug-run}"
		log_warning_msg "  start - starts system-wide vncserver service"
		log_warning_msg "  stop  - stops system-wide vncserver service"
		log_warning_msg "  restart, force-reload - starts a new system-wide vncserver service"
		log_warning_msg "  awaken - tell system-wide vncserver to start a poll cycle immediately"
		log_warning_msg "  debug-run [strace [strace options...]] - start a debug run of the"
		log_warning_msg "    system-wide vncserver service, optionally running it under strace"
		exit 1
		;;
esac

exit 0
