#!/bin/bash

    set -e

case "$1" in
 start)
   fifo=/tmp/video_fifo2
   if [ ! -e $fifo ]; then
   mkfifo $fifo
   fi

   dir=$HOME/archives/2011
   now=`date -R`
   file=$dir/video_test2.ogg

   ffmpeg -f video4linux2 -i /dev/video0 -f jack -i ffmpeg -r 20 -f ogg -vcodec libtheora -s 320x240 -b 380k -acodec libvorbis -ab 64k -ar 44100 -ac 1 -y $file -map 0.0 -map 1.0 &

   sleep 3
   jack_connect jack_rack:out_1 ffmpeg:input_1
   #jack_connect jack_rack:out_1 ffmpeg:input_2

   sleep 2
   cat $file | tee $file.ogg | oggfwd -d "TeleCaster Live Video Services" -g "Vocal"  -n "TeleCaster Live Video" localhost 8000 source2parisson /telecaster_live_video.ogg &
   ;;
 
 stop)
   jack_disconnect jack_rack:out_1 ffmpeg:input_1
#   jack_disconnect jack_rack:out_1 ffmpeg:input_2
   pkill -9 ffmpeg
   ;;
esac





